name: xsoulspace_analytics
publish_to: none
description: Analytics & crash reporting tools for the app

version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  firebase_analytics: ^11.3.3
  firebase_analytics_web: ^0.5.10+2
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  xsoulspace_foundation: ^0.0.5

dev_dependencies:
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.13
