name: xsoulspace_analytics
publish_to: none
description: Analytics & crash reporting tools for the app

version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"
resolution: workspace

dependencies:
  firebase_analytics: ^12.0.3
  firebase_analytics_web: ^0.6.0+3
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  xsoulspace_foundation: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
