# packages/yjs_server/pubspec.yaml
name: collaborative_todo_server
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.4.0
  logging: ^1.2.0 # Added for better logging

dev_dependencies:
  test: ^1.24.0
