name: ui_kit
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  core:
    path: ../core
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  google_fonts: ^6.2.1
  life_hooks: ^0.0.19
  provider: ^6.1.2
  sliver_tools: ^0.2.12
  tap_builder: ^0.5.0
  ui_locale:
    path: ../ui_locale
  universal_io: ^2.2.2
  yandex_ads_sdk:
    git:
      ref: "3.3"
      url: https://github.com/xsoulspace/word_by_word_game
      path: packages/yandex_ads_sdk

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  xsoulspace_lints: ^0.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/json/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  # - family: la_icons
  #   fonts:
  #     - asset: packages/ui_kit/fonts/la_icons.ttf
# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
