name: xsoulspace_monetization
description: A Flutter package for managing in-app purchases, subscriptions, and
  advertisements across multiple platforms.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.3"
resolution: workspace

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_rustore_billing: ^6.1.0
  freezed_annotation: ^2.4.4
  huawei_iap: ^6.13.0+302
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  xsoulspace_foundation: ^0.0.7
  yandex_mobileads: ^7.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.13

dependency_overrides:
  go_router: ^14.3.0
