name: xsoulspace_monetization
description: A Flutter package for managing in-app purchases, subscriptions, and
  advertisements across multiple platforms.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  from_json_to_json: ^0.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.2
  xsoulspace_foundation: ^0.3.0

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

dependency_overrides:
  go_router: ^16.2.5
