name: core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  equatable: ^2.0.5
  firebase_analytics: ^11.3.3
  firebase_analytics_web: ^0.5.10+2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_core_web: ^2.18.1
  firebase_crashlytics: ^4.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.1
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  life_hooks: ^0.0.19
  logger: ^2.4.0
  path_to_regexp: ^0.4.0
  provider: ^6.1.2
  quiver: ^3.2.2
  shared_preferences: ^2.3.2
  ui_kit:
    path: ../ui_kit
  ui_locale:
    path: ../ui_locale
  universal_io: ^2.2.2
  uuid: ^4.5.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  xsoulspace_lints: ^0.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
# assets:
#   - assets/images/
# fonts:
# - family: asgard_icons
#   fonts:
#     - asset: packages/ui_kit/fonts/asgard_icons.ttf
# - family: Poppins
#   fonts:
#     - asset: packages/ui_kit/fonts/Poppins-Regular.ttf
#       weight: 400
#     - asset: packages/ui_kit/fonts/Poppins-Bold.ttf
#       weight: 700
