name: daily-budget-planner
version: 0.2.0+7
summary: Give yourself quick insight of what amount of money can be spent in day / week
description: |
  Give yourself quick insight of what amount of money can be spent in day / week

  Features:

  Set budget, expanse and date of next budget - and get quick insight of what amount you can plan for daily and weekly expanses.
  Set budget for current week and get quick insight of what amount you can plan for the day expanse.
  Method and Story

  I've been struggling for years to trying orginise spendings and earnings into quickly orginizable and analysable system and this app - is what came from it. I've tried to fill Every Expense (maybe you too:D) - which is for me, were waste of time. In the same time I've noticed: every day I'm starting to know what amount I have, and question myself before purchasing everything - how much I can spend in day/week?

  So, since it's about planning, then lt's make it easier:

  Enter amount of money you left.
  Add required expenses sum (for example rent + subscriptins + credits payments)
  Set date, when next salary you expecting.
  Then the app will get quantity of days to that day, substruct expenses and this sum will be devided to days count. For example: Amount: 350 Expenses: 50 Today: 1th June Next Salary: 30th June

  Calculations: Total Sum: 350 - 50 = 300 Days count: 31 - 2 = 29 + 1 (today's day) = 30

  Amount for day: 300 / 30 = 10

  That's it:)

  Please notice: this is not financial advise, but I hope that maybe this method will be useful for you too:)

  ## Have an idea, improvements, or bugs?

  Join Discord - https://discord.gg/y54DpJwmAn

  Have fun and a great time!
icon: snap/gui/daily-budget-planner.svg
confinement: strict
base: core18
grade: stable

slots:
  dbus-daily-budget-planner:
    interface: dbus
    bus: session
    name: dev.xsoulspace.daily_budget_planner # adjust accordingly

apps:
  daily-budget-planner:
    command: daily_budget_planner
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy

    slots:
      - dbus-daily-budget-planner

# https://forum.snapcraft.io/t/failed-to-install-or-refresh-a-snap-flutter-does-not-exist/25623
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  daily-budget-planner:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
